# Generated by Django 5.0.2 on 2024-02-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0007_commande_produit_produits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='produits',
        ),
        migrations.AddField(
            model_name='commande',
            name='produits',
            field=models.ManyToManyField(to='magasin.produit'),
        ),
    ]
