# Generated by Django 5.0.2 on 2024-02-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0008_remove_produit_produits_commande_produits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='dateCde',
            field=models.DateField(default=0, null=True),
        ),
    ]
